<a href="https://colab.research.google.com/github/Gabriel-Moura06/ex_julio/blob/main/EXARUEJULI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#LISTA ARUANE
#19

import numpy as np
matriz = np.array([[1,2],
                  [3,4]])

print(matriz)

[[1 2]
 [3 4]]


In [ ]:
#20
a11 = int(input("Elemento [1, 1]: "))
a12 = int(input("Elemento [1, 2]: "))
a13 = int(input("Elemento [1, 3]: "))
a21 = int(input("Elemento [2, 1]: "))
a22 = int(input("Elemento [2, 2]: "))
a23 = int(input("Elemento [2, 3]: "))
a31 = int(input("Elemento [3, 1]: "))
a32 = int(input("Elemento [3, 2]: "))
a33 = int(input("Elemento [3, 3]: "))


matriz = [[a11, a12, a13], [a21, a22, a23], [a31, a32, a33]]

print(matriz[0])
print(matriz[1])
print(matriz[2])


Elemento [1, 1]: 1
Elemento [1, 2]: 2
Elemento [1, 3]: 3
Elemento [2, 1]: 4
Elemento [2, 2]: 5
Elemento [2, 3]: 6
Elemento [3, 1]: 7
Elemento [3, 2]: 8
Elemento [3, 3]: 9
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [ ]:
#21
import numpy as np

a11 = int(input("digite o elemento:"))
a12 = int(input("digite o elemento:"))
a21 = int(input("digite o elemento:"))
a22 = int(input("digite o elemento:"))

matriz = np.array([[a11,a12],
                  [a21,a22]])

print(matriz)
print("segunda matriz:")

a1 = int(input("digite o elemento:"))
a2 = int(input("digite o elemento:"))
a3 = int(input("digite o elemento:"))
a4 = int(input("digite o elemento:"))
matriz2 = np.array([[a1,a2],
                   [a3,a4]])

print(matriz2)

print("matriz resultante:")
resultante = (matriz) + (matriz2)
print(resultante)


digite o elemento:1
digite o elemento:2
digite o elemento:3
digite o elemento:4
[[1 2]
 [3 4]]
segunda matriz:
digite o elemento:5
digite o elemento:6
digite o elemento:7
digite o elemento:8
[[5 6]
 [7 8]]
matriz resultante:
[[ 6  8]
 [10 12]]


In [ ]:
#22
def dobro(numero):
  return numero *2

resultado = dobro(5)
print(f'o dobro do numero é:',resultado)

o dobro do numero é: 10


In [ ]:
#23
def par_impar(numero):
  if numero %2 ==0:
    print("o numero é par")
  if numero %2 !=0:
    print("o numero é impar")
    return numero
resultado = par_impar(11)
print(resultado)

o numero é impar
11


In [ ]:
#24
def impares(lista):
    somar = 0
    for i in lista:
        if i % 2 != 0:
            somar += i
    return somar

resultado = impares([1, 2, 3, 4])
print(resultado)


4


In [ ]:
#25
import math

numero = float(input("Digite um número para calcular sua raiz quadrada: "))

raiz_quadrada = math.sqrt(numero)

print(f' a raiz quadrada do numero é:',raiz_quadrada)


Digite um número para calcular sua raiz quadrada: 81
 a raiz quadrada do numero é: 9.0


In [ ]:
#26
from datetime import datetime

data_str = input("Digite uma data no formato dd/mm/aaaa: ")

data = datetime.strptime(data_str, "%d/%m/%Y")

dia_da_semana = data.strftime("%A")

print(f"A data {data_str} corresponde a um {dia_da_semana}.")


Digite uma data no formato dd/mm/aaaa: 16/09/2006
A data 16/09/2006 corresponde a um Saturday.


In [ ]:
#27
import random

numero = int(input("Digite um número: "))

numero_aleatorio = random.randint(1, numero)

print(numero_aleatorio)


Digite um número: 4
3


In [ ]:
#28
import random

numeros_aleatorios = []

for i in range(5):
    numeros_aleatorios.append(random.randint(1, 100))


print(numeros_aleatorios)


[42, 87, 38, 55, 18]


In [ ]:
#29
import random
import time

resultado = random.randint(1, 6)

print("Lançando o dado...")
time.sleep(2)

print(f"O resultado do lançamento do dado é: {resultado}")


Lançando o dado...
O resultado do lançamento do dado é: 2


In [ ]:
#30
with open("texto.txt", "w") as arquivo:
    arquivo.write("Python é incrível!")

print("Frase escrita com sucesso no arquivo texto.txt!")


Frase escrita com sucesso no arquivo texto.txt!


In [ ]:
#31

with open("texto.txt", "r") as arquivo:
    conteudo = arquivo.read()

print("Conteúdo do arquivo texto.txt:")
print(conteudo)


Conteúdo do arquivo texto.txt:
Python é incrível!


In [ ]:
#32
nome = input("Digite o nome: ")
telefone = input("Digite o telefone: ")

with open("contatos.txt", "a") as arquivo:
    arquivo.write(f"Nome: {nome}, Telefone: {telefone}\n")

print("Contato salvo com sucesso em contatos.txt!")


Digite o nome: gabriel
Digite o telefone: 999999
Contato salvo com sucesso em contatos.txt!


In [ ]:
#33
numero_str = input("Digite um número para dividir 100 por ele: ")

if numero_str.isnumeric():
    numero = float(numero_str)
    if numero == 0:
        print("Erro: Não é possível dividir por zero!")
    else:
        resultado = 100 / numero
        print(f"O resultado de 100 dividido por {numero} é {resultado}")
else:
    print("Erro: Você não digitou um número válido!")


Digite um número para dividir 100 por ele: 0
Erro: Não é possível dividir por zero!


In [ ]:
#LISTA JULIO:
#31
import numpy as np
matriz = np.array([[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20],
          [21,22,23,24,25]])

print(matriz)
print('------------------------------')
soma_linha_tres = sum(matriz[3])
print(f'a soma da linha 3 é:',soma_linha_tres)
somar_coluna_dois = matriz[0,2] + matriz[1,2] + matriz[2,2] + matriz[3,2]+ matriz[4,2]
print(f'a soma da coluna 2 é:',somar_coluna_dois)

somar_dia = matriz[0,0] + matriz [1,1] + matriz[2,2] + matriz[3,3] + matriz[4,4]
print(f'a soma das diagonais é:',somar_dia)

somar_dia_dois = matriz[0,4] + matriz[1,3] + matriz[2,2] + matriz[3,1] + matriz[4,0]
print(f'soma da diagonal secundaria é:',somar_dia_dois)

todos = np.sum(matriz)
print(f'a soma de todos é:',todos)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------------
a soma da linha 3 é: 90
a soma da coluna 2 é: 65
a soma das diagonais é: 65
soma da diagonal secundaria é: 65
a soma de todos é: 325


In [ ]:
#32
import numpy as np


matrizA = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24]
])

matrizB = np.array([
    [24, 23, 22, 21, 20, 19],
    [18, 17, 16, 15, 14, 13],
    [12, 11, 10, 9, 8, 7],
    [6, 5, 4, 3, 2, 1]
])


matrizS = matrizA + matrizB


matrizD = matrizA - matrizB

print("Matriz S:")
print(matrizS)

print("\nMatriz D:")
print(matrizD)


Matriz S:
[[25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]]

Matriz D:
[[-23 -21 -19 -17 -15 -13]
 [-11  -9  -7  -5  -3  -1]
 [  1   3   5   7   9  11]
 [ 13  15  17  19  21  23]]


In [ ]:
#33
import numpy as np
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

soma = 0
for i in range(2):
    for j in range(2):
        soma += a[i][j]
print(soma)

soma = a[2][2] + a[2][3] + a[3][2] + a[3][3]
print(soma)

soma3 = 0
for i in range(4):
    for j in range(i + 1):
        soma3 += a[i][j]

print(soma3)

soma4 = 0
for i in range(4):
    for j in range(4):
        if i == 0 or i == 3 or j == 0 or j == 3:
            soma4 += a[i][j]
print(soma4)


14
54
100
102


In [ ]:
#35
G = []
SL = [0] * 5
SC = [0] * 5


for i in range(5):
    linha = []
    for j in range(5):
        valor = int(input(f"G[{i}][{j}]: "))
        linha.append(valor)
        SL[i] += valor
        SC[j] += valor
    G.append(linha)

print("\nVetor SL (somas das linhas):", SL)
print("Vetor SC (somas das colunas):", SC)


G[0][0]: 2
G[0][1]: 2
G[0][2]: 2
G[0][3]: 2
G[0][4]: 2
G[1][0]: 2
G[1][1]: 2
G[1][2]: 2
G[1][3]: 2
G[1][4]: 2
G[2][0]: 2
G[2][1]: 2
G[2][2]: 2
G[2][3]: 2
G[2][4]: 2
G[3][0]: 2
G[3][1]: 2
G[3][2]: 2
G[3][3]: 2
G[3][4]: 2
G[4][0]: 2
G[4][1]: 2
G[4][2]: 2
G[4][3]: 2
G[4][4]: 2

Vetor SL (somas das linhas): [10, 10, 10, 10, 10]
Vetor SC (somas das colunas): [10, 10, 10, 10, 10]


In [4]:
#39
def somar(a, b):
    return a + b

def subtrair(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Erro: divisão por zero"
    return a / b

def calculadora():

    try:
        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))
    except ValueError:
        print("Erro: insira valores numéricos válidos.")
        return

    operacao = input("Escolha a operação: ")

    if operacao == '+':
        resultado = somar(num1, num2)
    elif operacao == '-':
        resultado = subtrair(num1, num2)
    elif operacao == '*':
        resultado = multiplicar(num1, num2)
    elif operacao == '/':
        resultado = dividir(num1, num2)
    else:
        print("Operação inválida.")
        return

    print(f"O resultado é: {resultado}")

calculadora()




Digite o primeiro número: 6
Digite o segundo número: 6
Escolha a operação: /
O resultado é: 1.0


In [7]:
#40
def multiplicar_por_somas(a, b):
    resultado = 0
    negativo = False

    if b < 0:
        b = -b
        negativo = True

    for i in range(int(b)):
        resultado += a

    return -resultado if negativo else resultado

r = multiplicar_por_somas(3,3)
print(r)

9


In [8]:
#41
def velocidade_media(distancia_metros, tempo_segundos):
    if tempo_segundos == 0:
        return "Erro"
    return distancia_metros / tempo_segundos


In [ ]:
#42
# Função de divisão
def divisao(a, b):
    if b == 0:
        return "Erro"
    return a / b

def velocidade_media(distancia_metros, tempo_segundos):
    return divisao(distancia_metros, tempo_segundos)



In [18]:
#43
def organizar_numeros(numero):
    numero_str = str(numero)

    crescente = ''.join(sorted(numero_str))

    decrescente = ''.join(sorted(numero_str, reverse=True))

    reverso = numero_str[::-1]

    print(f"Recebido: {numero}")
    print(f"Crescente: {crescente}")
    print(f"Decrescente: {decrescente}")
    print(f"Reverso: {reverso}")

organizar_numeros(123)



Recebido: 123
Crescente: 123
Decrescente: 321
Reverso: 321


In [20]:
#44
def converter_hora(hora24, minuto):
    if hora24 == 0:
        hora12 = 12
        periodo = 'A'
    elif hora24 < 12:
        hora12 = hora24
        periodo = 'A'
    elif hora24 == 12:
        hora12 = 12
        periodo = 'P'
    else:
        hora12 = hora24 - 12
        periodo = 'P'

    return hora12, minuto, periodo

def exibir_hora(hora12, minuto, periodo):
    sufixo = 'A.M.' if periodo == 'A' else 'P.M.'
    print(f"Hora convertida: {hora12}:{minuto:02d} {sufixo}")

while True:
    try:
        h = int(input("Digite a hora (0 a 23): "))
        m = int(input("Digite os minutos (0 a 59): "))

        if not (0 <= h <= 23 and 0 <= m <= 59):
            print("Hora ou minuto inválido.")
            continue

        hora12, minuto, periodo = converter_hora(h, m)
        exibir_hora(hora12, minuto, periodo)

        repetir = input("Deseja converter outro horário? (s/n): ").lower()
        if repetir != 's':
            print("Encerrando o programa.")
            break

    except ValueError:
        print("Entrada inválida. Digite apenas números inteiros.")


Digite a hora (0 a 23): 23
Digite os minutos (0 a 59): 23
Hora convertida: 11:23 P.M.
Deseja converter outro horário? (s/n): n
Encerrando o programa.


In [22]:
#45
import datetime

meses = [
    "janeiro", "fevereiro", "março", "abril", "maio", "junho",
    "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
]

def data_por_extenso(data_str):
    try:
        data = datetime.datetime.strptime(data_str, "%d/%m/%Y")

        dia = data.day
        mes = meses[data.month - 1]
        ano = data.year

        return f"{dia} de {mes} de {ano}"

    except ValueError:
        return None

testar = input("Digite uma data (DD/MM/AAAA): ")
resultado = data_por_extenso(testar)

if resultado:
    print("Data formatada:", resultado)
else:
    print("Data inválida.")


Digite uma data (DD/MM/AAAA): 20/3/2025
Data formatada: 20 de março de 2025
